// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsdnwklbmclqndxjihcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzZG53a2xibWNscW5keGppaGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDU2MDQsImV4cCI6MjA2OTEyMTYwNH0.4Vi07E8uNNwYeKMj3FHtSpuWT2qAzA7ZX2y15tpsJSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});